---
title: "Team Contract"
author: "Daniel Merigo"
date: "2023-03-31"
output: html_document
---

# **Teamwork Contract**

Members: Eric Tsai, Caesar Wong, Daniel Merigo, Zilong Yi

## **Expectations**

Group members are expected to submit their finished assigned work as a pull request by Friday 11:59 pm of that week. Code is expected to be properly tested and functioning before the pull request is submitted. Written sections should use proper spelling and grammar.

If a group member is unable to finish their work by the Friday deadline, please let the other members know by the Wednesday check-in so that others can help or redistribute work.

## **Meetings**

-   Formal, in-person meetings on Mondays 2-4pm (during lab)

    -   Understand requirements

    -   Delegate work

    -   Group discussions

    -   Work on things as a group

-   Slack meeting on Friday at 11am for check-in and to see if any remaining tasks need to be finished, address issues or bugs and provide help if needed.\

## **Communication**

Communication will take place informally on Slack and formally through GitHub Issues.

## **Reviews**

All pull requests should be reviewed by at least 1 member (ideally 1 more in addition to the proofreader). Pull requests should be submitted before Friday 11:59 pm of each week.\

## **Breach of Contract**

If the terms of the contract are violated, we will use a three stage warning system:

1.  Slack warning outlining the violation and a reminder of the terms of the contract.

2.  In-person meeting to discuss the issues/violations and attempt to find a solution.

3.  Reaching out to TAs/staff to discuss the issues.
